### ISSUE TITLE
Use transactions during initial sync for better speed

### ISSUE THREAD

**Issue by sergiogiogio** [alex-phillips/node-clouddrive#11]
Hello - I have 46k+ files in my cloud drive and the initial sync did not complete within 15min (I killed it). It is heavily writing to the disk, probably executing single self-committing insert statements. Please consider committing only every 50 or so statements in order to speed up sync.

**Comment by alex-phillips** [comment]
@sergiogiogio Thanks for the feedback! I've added this into the master branch (will probably tag a new release soon). Thanks for the input! You can find the commit here: https://github.com/alex-phillips/clouddrive-node/commit/7aad77c95e7eae8cee4da8d6c4ffcdc5c16598e9

FYI: adding transactions decreased the total sync time of my personal account more than 75%!
