### ISSUE TITLE
failed to init

### ISSUE THREAD

**Issue by pahud** [alex-phillips/node-clouddrive#14]
Hello,

I got the error message on init phase. Did I miss anything?

```
pahud-mpb:~ pahud$ clouddrive init
For the one-time initial authorization, a browser tab will be opened to 'https://data-mind-687.appspot.com/clouddrive'. Accept the authorization and paste in the response into this application.
? token:  "https://data-mind-687.appspot.com/clouddrive?code=ANZAKkmNOXUEOvmXXXXX&scope=clouddrive%3Aread+clouddrivFailed to authenticate with Amazon Cloud Drive: 
{ error_description: 'The request is missing a required parameter : client_id',
  error: 'invalid_request' }
pahud-mpb:~ pahud$ 
```

**Comment by alex-phillips** [comment]
@pahud The token you should paste is was is printed in the browser window after you authorize the app through Amazon, not the URL you are redirected to.

**Comment by pahud** [comment]
Hello @alex-phillips 

After authorization I got the JSON like this
`REDACTED`

If I paste the access_token then I got this

`REDACTED`

ideas?

**Comment by alex-phillips** [comment]
@pahud You need to paste in the entire response in the browser including the access token, expire time, etc.

I've also edited your comment above to remove your access token. That's not something you want publicly displayed.

**Comment by pahud** [comment]
it works! thank you so much!

**Comment by alex-phillips** [comment]
No problem!
