### ISSUE TITLE
Feature Request: md5 check all contents in directory

### ISSUE THREAD

**Issue by djlombar89** [alex-phillips/node-clouddrive#16]
Would be nice to have a command to scan the contents of an entire directly and verify all files are complete and identical.  For directories containing hundreds or thousands of files this would be a pain to do manually.

**Comment by alex-phillips** [comment]
This would essentially just be the same check of uploading a file or directory without actually making the HTTP request. It would be a lot of output depending on the amount of files.

Maybe use different verbosity levels to determine which states of files to show?

**Comment by alex-phillips** [comment]
Also, do we want to check if the nodes exist at a specified destination or at all remotely?

**Comment by djlombar89** [comment]
Rather a check for incomplete files..it would be nice to have verification for those paranoid like myself that all files were successfully uploaded and without any corruption.  At all remotely at least and specified destination would be a nice to have.

**Comment by alex-phillips** [comment]
I've added an `exists` command in the master branch. Let me know if this solves your needs / wants

**Comment by iliakan** [comment]
Any progress on that? The current version supports the functionality? Need it really.

**Comment by alex-phillips** [comment]
I'll need to modify this slightly this weekend. Currently if you check a local directory if it exists, it doesn't upload any files, but it does create the the directory structure remotely which I don't think is a good thing.

**Comment by alex-phillips** [comment]
I've just uploaded changes to the `master` branch with the `exists` command that doesn't make unnecessary files and directories. I'll push this to a new release after a few more tests

**Comment by alex-phillips** [comment]
The `exists` command is now live and in the newest version (0.4.0).
