### ISSUE TITLE
sync got Unhandled rejection Error

### ISSUE THREAD

**Issue by pahud** [alex-phillips/node-clouddrive#18]
Hello,

I got unhandled rejection error when I sync, anyway to fix it?

pahud@lz ~ $ sudo clouddrive sync

> Syncing... ⠏Unhandled rejection Error: insert into "nodes" ("created", "id", "kind", "md5", "modified", "name", "raw_data", "status") values ('2016-01-03T05:46:54.370Z', 'c7XkWsp5QcyScC2pcqyM9A', 'FOLDER', NULL, '2016-01-03T05:47:21.204Z', NULL, '{\"version\":9,\"isShared\":false,\"createdDate\":\"2016-01-03T05:46:54.370Z\",\"modifiedDate\":\"2016-01-03T05:47:21.204Z\",\"eTagResponse\":\"YTO3IJFT4Fs\",\"createdBy\":\"CloudDriveDesktop\",\"id\":\"c7XkWsp5QcyScC2pcqyM9A\",\"parents\":[\"wpuA-SHRTECPlME0ARkkvA\"],\"restricted\":false,\"kind\":\"FOLDER\",\"labels\":[],\"status\":\"AVAILABLE\"}', 'AVAILABLE') - SQLITE_CONSTRAINT: NOT NULL constraint failed: nodes.name

**Comment by alex-phillips** [comment]
Somehow, a node got created with no name (in this case, id `c7XkWsp5QcyScC2pcqyM9A`). You can try and track it down by looking at its parent in the web interface [https://www.amazon.com/clouddrive/folder/wpuA-SHRTECPlME0ARkkvA](https://www.amazon.com/clouddrive/folder/wpuA-SHRTECPlME0ARkkvA). The API does not allow nodes to be created without a name, so my guess is something weird happened when uploading by other means.

If you can find it in the web interface, you should be able to rename it and sync again.

**Comment by pahud** [comment]
thank you!!
