### ISSUE TITLE
got SyntaxError: Unexpected token ILLEGAL in current master branch

### ISSUE THREAD

**Issue by pahud** [alex-phillips/node-clouddrive#19]
I just install with 

```
sudo npm install -g git+https://github.com/alex-phillips/node-clouddrive.git
```

and I got this error:

> pahud-mb12:~ pahud$ clouddrive 
> 
> /usr/local/share/npm/lib/node_modules/clouddrive/bin/clouddrive.js:10
>   banner = `   ________                __   ____       _
>            ^
> SyntaxError: Unexpected token ILLEGAL
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3

please help

**Comment by alex-phillips** [comment]
What version of node are you running? I've updated the code with a better version check, but with the `master` branch, version 4.0.0 or higher is required.

**Comment by pahud** [comment]
oh, yes my node version is too old. Have upgraded to 4.x and it works.

thanks.
