### ISSUE TITLE
Request: Add Library documentation to readme

### ISSUE THREAD

**Issue by bugs181** [alex-phillips/node-clouddrive#23]
As it stands, I only see CLI documentation on the Github repo README. According to the title "Amazon Cloud Drive CLI _and SDK_", I'm assuming that what I'm after is possible.

I'd like to be able to "drive" this library inside of another node project. What steps (`require`, etc) should I take to get this functional? I'm assuming I could build a wrapper which just runs the CLI commands but I've never liked that approach. I think it feels too clunky, and that leads us back to the issue of the OS threading model by running multiple processes. The whole point of using node in the first place! ;)

Appreciate any help you can provide.

**Comment by alex-phillips** [comment]
Sorry for the late reply: this is a work in progress so I apologize that not everything is fully documented yet. That being said, any PRs for this would be much appreciated!!

In the meantime, the cli that ships with the project implements the project as it should be implemented as an SDK in other projects. I would recoment starting with `InitCommand.js`. Note that all commands extend `Command.js` which is where the majority of all initializing takes place including the account, local cache, etc.

I hope this helps. If you have any specifics, please let me know and I'd be happy to help. I currently don't have an ETA for when the SDK docs will be up.
