### ISSUE TITLE
Cannot resolve ID which have hyphenation at the first

### ISSUE THREAD

**Issue by xmhscratch** [alex-phillips/node-clouddrive#25]
Resolve command doesn't works against ID have hyphenation at first.
For example: `clouddrive resolve "-qDILF9ZZTqGwBzvdAFz3"`

**Comment by alex-phillips** [comment]
The best way to handle these types of IDs is to put it in quotes with a space before it. Ex: clouddrive resolve " -12345"

**Comment by xmhscratch** [comment]
Thanks for the quick replay. I've found this problem come from yargs package cannot parse string with pre hyphenation properly. A little bit tricky is to add a space at first instead of a hyphenation :+1:
