### ISSUE TITLE
Doesn't work for large folders

### ISSUE THREAD

**Issue by iliakan** [alex-phillips/node-clouddrive#26]
I installed it and run to download a large folder.

After a short time I started to get "Response returned with status code 401" errors, guess token expired or something.

**Comment by alex-phillips** [comment]
Were any files able to successfully download? There is a retry mechanism already built-in.

**Comment by alex-phillips** [comment]
Also what is the output when you run the init command.

**Comment by iliakan** [comment]
Yeah, things were working fine until I started to get 401s.

**Comment by iliakan** [comment]
init command was fine.
Sorry for not answering immediately, I just didn't think the project is well-supported.

**Comment by alex-phillips** [comment]
I've added a bunch of updates - could you pull down the master branch and see if that solves your issue?

**Comment by iliakan** [comment]
Now I tried to download the files one-by-one, like this `clouddrive download -vvv $file`.

And here's the issue.
1) I have in config:

```
cli.colors           = false
cli.progressBars     = false
cli.progressInterval = true
```

Now, the progress bar is not seen. BUT when I redirect the output to a log-file, I have a bunch of extra "progress" lines. It's hard to read the log file.

The lines are like this (using `less` for visible esc codes):

```
ESC[?25lDownloading webpack-screencast.tgz.aes.part07.rar
ESC[?25lESC[1000DESC[KESC[1AESC[1000DESC[KDownloading webpack-screencast.tgz.aes.part07.rar
ESC[?25lESC[1000DESC[KESC[1AESC[1000DESC[KDownloading webpack-screencast.tgz.aes.part07.rar
ESC[?25lESC[1000DESC[KESC[1AESC[1000DESC[KDownloading webpack-screencast.tgz.aes.part07.rar
ESC[?25lESC[1000DESC[KESC[1AESC[1000DESC[KDownloading webpack-screencast.tgz.aes.part07.rar
ESC[?25lESC[1000DESC[KESC[1AESC[1000DESC[KDownloading webpack-screencast.tgz.aes.part07.rar
```

2) The download breaks sometimes. The clouddrive exits with exit code 137 or 1 and no other messages. I don't know what to think.

**Comment by alex-phillips** [comment]
@iliakan I've added significantly more verbose logging (and support for logging to a file). I've never encountered the error your describing, but I'd like to get to the bottom of it. Pull down master and let me know if you have the same issue and attach the logs if you do.

**Comment by alex-phillips** [comment]
Closing the issue. If you can provide any more information, I can look into this, but I haven't been able to replicate it.

**Comment by iliakan** [comment]
yeah sorry there was a big delay before your answer, so I switched to another tool and changed the environment, forgot how it was.
