### ISSUE TITLE
"Error: Node cannot be saved with no name" while  sync'ing

### ISSUE THREAD

**Issue by dcoon** [alex-phillips/node-clouddrive#40]
Anyone seen this?  Happens during sync.  Tried clearcache and resyncing but same behavior.  Version 0.5.0 installed via npm.  It's happening in SQL.js when it sees a node with a blank name that isn't root.  

Davids-MBP:~ dcoon$ clouddrive -vv sync
debug	: Running SyncCommand
debug	: Connecting to databsae
debug	: Successfully conncted to databse.
debug	: Successfully loaded account.
verbose	: Requesting account:endpoints endpoint
debug	: HTTP Request: GET 'https://cdws.us-east-1.amazonaws.com/drive/v1/account/endpoint'
debug	: Response returned with status code 200.
debug	: Successfully authenticated with Amazon account.
verbose	: Requesting changes:get endpoint
debug	: HTTP Request: POST 'https://cdws.us-east-1.amazonaws.com/drive/v1/changes'
debug	: Response returned with status code 200.
debug	: Received 24 parts.
error	: Error: Node cannot be saved with no name (node ID: #######)
debug	: Exiting with code 1

**Comment by dcoon** [comment]
ACD must have changed the response format slightly. Quick hack to make it work again, but disables some error checking.  YMMV.  

http://pastebin.com/raw/zSqTrase

**Comment by alex-phillips** [comment]
Interesting. I did a fresh install and did not run into this issue.

**Comment by alex-phillips** [comment]
Going to close this for now since I can't replicate. Per Amazon's API guidelines, no node cannot have no name except for the default 'root' node.

If this persists and/or you have any additional information, we can reopen the issue.

**Comment by dcoon** [comment]
Thanks.  Sorry for not replying.  Busy with the holidays.  If I can
recreate, I'll send better instructions. David

**Comment by alex-phillips** [comment]
No problem, hopefully we can get this resolved!
