### ISSUE TITLE
First run clouddrive config throws: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by himesh-neo** [alex-phillips/node-clouddrive#42]
OS: CentOS release 6.8 (Final)
Node Version: 6.9.2

Steps to reproduce
1. npm install -g clouddrive
2. clouddrive config

Throws following error:

![image](https://cloud.githubusercontent.com/assets/4416934/21564347/80dc3dba-ceb2-11e6-9c9f-193b4b119ff7.png)

**Comment by alex-phillips** [comment]
What version of clouddrive are you running?

**Comment by himesh-neo** [comment]
clouddrive@0.6.0

UPDATE: issue persists after upgrading to 0.6.1

**Comment by himesh-neo** [comment]
I'm running it as 'root'. This statement is failing:
> const username = homedir.split('/')[2];

On file: clouddrive/node_modules/env-paths/index.js.

I'll raise a bug on 'env-paths'

**Comment by alex-phillips** [comment]
Solved with PR #43
