### ISSUE TITLE
Strange slow upload behavior

### ISSUE THREAD

**Issue by hubsmoke** [alex-phillips/node-clouddrive#44]
The upload seems to stop and start constantly, making the upload really slow. Video attached

https://www.youtube.com/watch?v=AIXvFvn5Bbg&feature=youtu.be

I haven't had problems with uploading previously. Just updated to the latest, issue persists

**Comment by alex-phillips** [comment]
It looks like there's an error when I try to play the YouTube video.

**Comment by alex-phillips** [comment]
Nevermind, I got the video to work. I'll see what I can find out.

**Comment by alex-phillips** [comment]
@hubsmoke In the meantime, I've just published a new release fixing 2 memory leaks which could be affecting your performance. Do an update and let me know if the problem persists. Thanks!

**Comment by hubsmoke** [comment]
Just tried v0.6.4 and still seeing this behavior

**Comment by hubsmoke** [comment]
Maybe this is as simple as the 'estimated time' not being updated correctly. For all I know the upload is happening as fast as it can. However, it is pretty slow spending like 15minutes for 125mb file

**Comment by alex-phillips** [comment]
What are your normal bandwidth speeds if you run a speed test?

**Comment by hubsmoke** [comment]
Looks like I'm on the upload struggle bus. Would this explain the strange behavior I'm seeing in the client?

<img width="392" alt="screenshot 2017-02-15 19 55 22" src="https://cloud.githubusercontent.com/assets/278886/23006778/c4bef286-f3b8-11e6-9369-fd056088fa8d.png">

**Comment by alex-phillips** [comment]
Definitely, that speed is quite slow. But if it is a problem with the app, I do want to try and track it down.

Were you always experiencing these slow issues? Another test you can run is to upload the same file via the web interface and see if it takes just as long. If its about the same, then we know the upload code is correct, but maybe like you said the ETA is inaccurate.

**Comment by alex-phillips** [comment]
Closing this. Re-open if the issue still exists.
