### ISSUE TITLE
429 HTTP Errors

### ISSUE THREAD

**Issue by davidfekke** [alex-phillips/node-clouddrive#46]
I am getting a lot of 429 HTTP Errors. 

`Response code 429 (Too Many Requests)`. Is anyone else getting this error?

**Comment by alex-phillips** [comment]
It looks like issues with their API. Not tied to a single account. I've submitted a support ticket just in case.

**Comment by davidfekke** [comment]
Thanks Alex. Seems to be working better this morning.
