### ISSUE TITLE
Whitelisting an App

### ISSUE THREAD

**Issue by williamkapke** [alex-phillips/node-clouddrive#47]
It doesn't look like Amazon leaves any option for folks to be independent of an "App" for authentication.

My worry is that the server you provide will, at some point, go down. There's no redundancy. No one should expect this to be YOUR problem. So.... I've been researching how to create my own "App" and stand up my own authentication server (like your [data-mind-687.appspot.com](https://github.com/alex-phillips/clouddrive-endpoint)).

I've created a Security Profile... but what I can't figure out is how to get whitelisted for the scopes? Any tips?

Do I need to submit the app first?

**Comment by alex-phillips** [comment]
@williamkapke Honestly, it's been a while since I white listed mine. But I BELIEVE that you do need to submit it first.

**Comment by alex-phillips** [comment]
It looks like Amazon has quit whitelisting new apps and current apps don't necessarily have access to the 'new' API. Not sure of the future of the existing API, but I will keep this project updated as long as I have access.
