### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by marekk1717** [alex-phillips/node-clouddrive#48]
I'm trying to download my backup from Amazon Cloud Drive using "download" option, but operation ends with error 400 after few minutes. 
When I paste url into web browser, file is downloaded successfully.
> HTTP Request: GET 'https://content-na.drive.amazonaws.com/cdproxy/nodes/XXXXXXXXXXXXXXXX/content'

It's wort to mention that I'm trying to download recursively folder with multiple nested subfolders.

**Comment by Tangoes** [comment]
Same here, but when trying to UPLOAD a single file.

**Comment by alex-phillips** [comment]
@marekmkmk What version are you running? Also, what is the exact command you're using?

**Comment by Tangoes** [comment]
That was an amazon eu issue for me, nothing related to clouddrive
