### ISSUE TITLE
 HTTPError: Response code 404 (Not Found). Reauthenticating and retrying.

### ISSUE THREAD

**Issue by Kedryn** [alex-phillips/node-clouddrive#49]
When downloading the 13th episode from one folder of my ACD, i got repeated

 HTTPError: Response code 404 (Not Found). Reauthenticating and retrying.

but the file exists.

**Comment by alex-phillips** [comment]
I would run a sync (maybe even a `clearcache` and sync). It's possible that the ID could have been changed compared to whats in the database. This has happened to me in the past when an upload got interrupted. After continuing the upload, it created a new entry with a new ID (leaving the old one in a `pending` state).

Let me know if that doesn't solve your issue. If it doesn't, run the download command in debug mode (`-vv`) and paste in your logs.
