### ISSUE TITLE
Please echo out the URL for people without UI's

### ISSUE THREAD

**Issue by seals55** [alex-phillips/node-clouddrive#6]
HI,
I was able to authenticate using a second computer, but had to look through the source code to find the url to go to

 open('https://data-mind-687.appspot.com/clouddrive');

if you could also echo that out, it would be much easier to navigate to when there is no UI

Thanks,
Chris

**Comment by alex-phillips** [comment]
@seals55 Great point! I didn't think about that. It's now pushed to master and will be included in the next tagged release (probably very soon to push out bug fixes, etc.).

**Comment by seals55** [comment]
great, thanks!

**Comment by alex-phillips** [comment]
@seals55 New release is tagged!
