### ISSUE TITLE
Enhancement Request: Built-in support for EncFS encryption

### ISSUE THREAD

**Issue by dellipse** [alex-phillips/node-clouddrive#8]
The one thing that every ACD client I have found is missing is the ability to encrypt files before they are sent to ACD, so ACD has 'zero knowledge' of your content.

Would you be able to look at adding this feature?

**Comment by alex-phillips** [comment]
@dellipse I've worked but haven't gotten much ground implementing libFuse into this project, however, the newest version (0.6) how has support for encrypting the files / filenames on upload (and decryption on download). Hopefully this will suffice for now. If someone else is willing to help out with the libfuse portion, we can revisit this.
